- name: Create Postgresql cluster
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: "acid.zalan.do/v1"
      kind: postgresql
      metadata:
        name: "{{ zalando_postgresql_cluster_name }}"
        namespace: "{{ zalando_postgresql_cluster_namespace }}"
      spec: "{{ _zalando_postgresql_cluster_spec | combine(zalando_postgresql_cluster_spec, recursive=True) }}"

- name: Wait until Postgresql cluster is ready
  kubernetes.core.k8s_info:
    api_version: acid.zalan.do/v1
    kind: postgresql
    name: "{{ zalando_postgresql_cluster_name }}"
    namespace: "{{ zalando_postgresql_cluster_namespace }}"
  register: _postgresql_cluster_info
  until: _postgresql_cluster_info.resources[0].status.PostgresClusterStatus == "Running"
  retries: 60
  delay: 10
