_zalando_postgresql_cluster_spec:
  teamId: "{{ zalando_postgresql_cluster_team }}"
  volume:
    size: 8Gi
  numberOfInstances: 3
  users:
    zalando:
      - superuser
      - createdb
    atmosphere: []
  databases:
    atmosphere: atmosphere  # dbname: owner
  postgresql:
    version: "15"
  patroni:
    initdb:
      locale: C
      lc-collate: C
      lc-ctype: C
      encoding: UTF8
