# Copyright (c) 2022 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

_keystone_helm_values:
  endpoints: "{{ openstack_helm_endpoints }}"
  images:
    tags: "{{ atmosphere_images | vexxhost.atmosphere.openstack_helm_image_tags('keystone') }}"
  pod:
    replicas:
      api: 3
  conf:
    keystone:
      DEFAULT:
        log_config_append: null
      auth:
        methods: password,token,openid,application_credential
      cors:
        allowed_origins: "*"
      federation:
        assertion_prefix: OIDC-
        remote_id_attribute: OIDC-iss
        # TODO(mnaser): Lookup using openstack_helm_endpoints
        trusted_dashboard: "https://{{ openstack_helm_endpoints_horizon_api_host }}/auth/websso/"
      oslo_messaging_notifications:
        driver: noop
    ks_domains:
      atmosphere:
        identity:
          driver: keycloak
        keycloak:
          server_url: "{{ keystone_keycloak_server_url }}"
          user_realm_name: "{{ keystone_keycloak_user_realm_name }}"
          client_id: "{{ keystone_keycloak_client_id }}"
          username: "{{ keystone_keycloak_admin_user }}"
          password: "{{ keystone_keycloak_admin_password }}"
          realm_name: "{{ keystone_keycloak_realm }}"
  manifests:
    job_credential_cleanup: false
    ingress_api: false
    service_ingress_api: false
