# Copyright (c) 2022 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

_keystone_helm_values:
  endpoints: "{{ openstack_helm_endpoints }}"
  images:
    tags: "{{ atmosphere_images | vexxhost.atmosphere.openstack_helm_image_tags('keystone') }}"
  pod:
    replicas:
      api: 3
  conf:
    keystone:
      DEFAULT:
        log_config_append: null
      auth:
        methods: password,token,openid,application_credential
      cors:
        allowed_origins: "*"
      openid:
        remote_id_attribute: HTTP_OIDC_ISS
      federation:
        # TODO(mnaser): Lookup using openstack_helm_endpoints
        trusted_dashboard: "https://{{ openstack_helm_endpoints_horizon_api_host }}/auth/websso/"
      oslo_messaging_notifications:
        driver: noop
    wsgi_keystone: |
      LoadModule headers_module /usr/lib/apache2/modules/mod_headers.so
      Listen 0.0.0.0:5000
      TransferLog /dev/stdout
      ErrorLog /dev/stderr
      <VirtualHost *:5000>
        # WSGI
        WSGIDaemonProcess keystone-public processes=4 threads=1 user=keystone group=keystone display-name=%{GROUP}
        WSGIProcessGroup keystone-public
        WSGIScriptAlias / /var/www/cgi-bin/keystone/keystone-wsgi-public
        WSGIApplicationGroup %{GLOBAL}
        WSGIPassAuthorization On
        # OIDC
        OIDCClaimPrefix "OIDC-"
        OIDCResponseType "id_token"
        OIDCScope "{{ keystone_oidc_scopes }}"
        OIDCSSLValidateServer "{{ keystone_oidc_ssl_validate_server }}"
        OIDCProviderMetadataURL {{ keystone_oidc_provider_metadata_url }}
        OIDCOAuthVerifyJwksUri {{ keystone_oidc_oauth_verify_jwks_uri }}
        OIDCClientID {{ keystone_oidc_client_id }}
        OIDCClientSecret {{ keystone_oidc_client_secret }}
        OIDCCryptoPassphrase {{ keystone_oidc_crypto_passphrase }}
        OIDCRedirectURI {{ keystone_keycloak_redirect_uri }}
        OIDCRedirectURLsAllowed ^https://{{ openstack_helm_endpoints_horizon_api_host }}/auth/logout/$
        <Location /v3/OS-FEDERATION/identity_providers/atmosphere/protocols/openid/auth>
          Require valid-user
          AuthType openid-connect
        </Location>
        <Location /v3/auth/OS-FEDERATION/identity_providers/atmosphere/protocols/openid/websso>
          Require valid-user
          AuthType openid-connect
        </Location>
        <Location /v3/auth/OS-FEDERATION/websso/openid>
          Require valid-user
          AuthType openid-connect
        </Location>
        # NOTE(mnaser): These are Atmosphere specific settings.
        OIDCSessionType client-cookie:store_id_token
        OIDCXForwardedHeaders X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
      </VirtualHost>
    ks_domains: "{{ keystone_domains | to_ks_domains }}"
  manifests:
    job_credential_cleanup: false
    ingress_api: false
    service_ingress_api: false
