# Copyright (c) 2022 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

galaxy_info:
  author: VEXXHOST, Inc.
  description: Ansible role for OpenStack Keystone
  license: Apache-2.0
  min_ansible_version: 5.5.0
  standalone: false
  platforms:
    - name: Ubuntu
      versions:
        - focal

dependencies:
  - role: defaults
  - role: openstacksdk
  - role: openstack_helm_endpoints
    vars:
      openstack_helm_endpoints_chart: keystone
  - role: vexxhost.kubernetes.upload_helm_chart
    vars:
      upload_helm_chart_src: "{{ keystone_helm_chart_path }}"
      upload_helm_chart_dest: "{{ keystone_helm_chart_ref }}"
  - role: keycloak_client
    vars:
      keycloak_client_id: "{{ keystone_keycloak_client_id }}"
      keycloak_client_secret: "{{ keystone_keycloak_client_secret }}"
      keycloak_client_admin_url: "https://{{ openstack_helm_endpoints_keystone_api_host }}"
      keycloak_client_base_url: "https://{{ openstack_helm_endpoints_keystone_api_host }}"
      keycloak_client_redirect_uris:
        - "{{ keystone_keycloak_redirect_uri }}"
        - "https://{{ openstack_helm_endpoints_horizon_api_host }}/auth/logout/"
      keycloak_client_root_url: "https://{{ openstack_helm_endpoints_keystone_api_host }}"
      keycloak_client_web_origins: ["https://{{ openstack_helm_endpoints_keystone_api_host }}"]
      keycloak_client_standard_flow_enabled: true
      keycloak_client_implicit_flow_enabled: true
